django_app/base/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'base'

urlpatterns = [
	#pagina inicial
	path('', views.index, name='index'),
	path('new_graph/', views.new_graph, name='new_graph'),
	path('graphs/', views.graphs, name='graphs'),
	path('entrytemperature/', views.entrytemperature, name='entrytemperature'),
	path('entryhumidity/', views.entryhumidity, name='entryhumidity'),
	path('calibrate/', views.recalculate, name='recalculate'),
	path('longgraphic/', views.longGraphic, name='longGraphic'),
]

django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

django_app/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'

urlpatterns = [
    # Página de login
    path('login/', LoginView.as_view(template_name='users/login.html'), name= 'login'),
    # Página de Logout
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('base:index')), name='logout'),
    path('register/', views.register, name='register'),
]

django_app/base/models.py
from django.db import models

class temperature(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	x0 = models.CharField(max_length=25)
	x1 = models.CharField(max_length=25)
	x2 = models.CharField(max_length=25)
	x3 = models.CharField(max_length=25)
	x4 = models.CharField(max_length=25)
	x5 = models.CharField(max_length=25)
	x6 = models.CharField(max_length=25)
	x7 = models.CharField(max_length=25)
	x8 = models.CharField(max_length=25)
	x9 = models.CharField(max_length=25)
	x10 = models.CharField(max_length=25)
	x11 = models.CharField(max_length=25)
	x12 = models.CharField(max_length=25)
	x13 = models.CharField(max_length=25)
	x14 = models.CharField(max_length=25)
	x15 = models.CharField(max_length=25)
	x16 = models.CharField(max_length=25)
	x17 = models.CharField(max_length=25)
	x18 = models.CharField(max_length=25)
	x19 = models.CharField(max_length=25)
	x20 = models.CharField(max_length=25)
	x21 = models.CharField(max_length=25)
	x22 = models.CharField(max_length=25)
	x23 = models.CharField(max_length=25)
	x24 = models.CharField(max_length=25)
	media = models.CharField(max_length=25)
	sigma = models.CharField(max_length=25)
	def __str__(self):
		return str(self.date)

class humidity(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	x0 = models.CharField(max_length=25)
	x1 = models.CharField(max_length=25)
	x2 = models.CharField(max_length=25)
	x3 = models.CharField(max_length=25)
	x4 = models.CharField(max_length=25)
	x5 = models.CharField(max_length=25)
	x6 = models.CharField(max_length=25)
	x7 = models.CharField(max_length=25)
	x8 = models.CharField(max_length=25)
	x9 = models.CharField(max_length=25)
	x10 = models.CharField(max_length=25)
	x11 = models.CharField(max_length=25)
	x12 = models.CharField(max_length=25)
	x13 = models.CharField(max_length=25)
	x14 = models.CharField(max_length=25)
	x15 = models.CharField(max_length=25)
	x16 = models.CharField(max_length=25)
	x17 = models.CharField(max_length=25)
	x18 = models.CharField(max_length=25)
	x19 = models.CharField(max_length=25)
	x20 = models.CharField(max_length=25)
	x21 = models.CharField(max_length=25)
	x22 = models.CharField(max_length=25)
	x23 = models.CharField(max_length=25)
	x24 = models.CharField(max_length=25)
	media = models.CharField(max_length=25)
	sigma = models.CharField(max_length=25)
	def __str__(self):
		return str(self.date)

class graphic(models.Model):
	tipo = models.BooleanField(default=False) #False = Humidity // True = Temperature
	date_added = models.DateTimeField(auto_now_add=True)
	date1 = models.DateTimeField(auto_now_add=False)
	date2 = models.DateTimeField(auto_now_add=False)
	img = models.ImageField(upload_to='static/graphs/', blank=True)
	cp = models.CharField(max_length=25)
	cpk = models.CharField(max_length=25)
	dpm = models.CharField(max_length=25)
	LC = models.CharField(max_length=25)
	LSC = models.CharField(max_length=25)
	LIC = models.CharField(max_length=25)
	LCs = models.CharField(max_length=25)
	LSCs = models.CharField(max_length=25)
	LICs = models.CharField(max_length=25)
	LSE = models.CharField(max_length=25)
	LIE = models.CharField(max_length=25)
	rule1m = models.BooleanField(default=False)
	rule2m = models.BooleanField(default=False)
	rule3m = models.BooleanField(default=False)
	rule4m = models.BooleanField(default=False)
	rule1s = models.BooleanField(default=False)
	rule2s = models.BooleanField(default=False)
	rule3s = models.BooleanField(default=False)
	rule4s = models.BooleanField(default=False)
	def __str__(self):
		return str(self.date_added)

class globalvar(models.Model):
	name = models.CharField(max_length=25)
	value = models.CharField(max_length=25)
	def __str__(self):
		return str(self.name)

class longgraphic(models.Model):
	tipo = models.BooleanField(default=False) #False = Humidity // True = Temperature
	img = models.ImageField(upload_to='static/graphs/', blank=True)
	cp = models.CharField(max_length=25)
	cpk = models.CharField(max_length=25)
	dpm = models.CharField(max_length=25)
	LC = models.CharField(max_length=25)
	LSC = models.CharField(max_length=25)
	LIC = models.CharField(max_length=25)
	LCs = models.CharField(max_length=25)
	LSCs = models.CharField(max_length=25)
	LICs = models.CharField(max_length=25)
	LSE = models.CharField(max_length=25)
	LIE = models.CharField(max_length=25)
	rule1m = models.BooleanField(default=False)
	rule2m = models.BooleanField(default=False)
	rule3m = models.BooleanField(default=False)
	rule4m = models.BooleanField(default=False)
	rule1s = models.BooleanField(default=False)
	rule2s = models.BooleanField(default=False)
	rule3s = models.BooleanField(default=False)
	rule4s = models.BooleanField(default=False)
	def __str__(self):
		return str(self.cp)

django_app/base/forms.py
from django import forms
from .models import graphic
from datetime import datetime

# ~ class graphicForm(forms.ModelForm):
	# ~ class Meta:
		# ~ model = graphic
		# ~ fields = ['year','month','day','hour','minu','year1','month1','day1','hour1','minu1']
		# ~ labels = {'year':'Ano Inicial', 'month':'Mês Inicial','day':'Dia Inicial','hour':'Hora Inicial','minu':'Minuto Inicial','year1':'Ano Final', 'month1':'Mês Final','day1':'Dia Final','hour1':'Hora Final','minu1':'Minuto Final'}

# ~ class graphicForm2(forms.Form):
	# ~ date = forms.DateTimeField(widget=forms.SelectDateWidget,initial=datetime.now())

django_app/base/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import graphic, humidity, temperature, globalvar, longgraphic
import graph
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.db import models
import numpy as np
from django.utils.dateparse import parse_datetime
import pytz
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseNotFound
import dateutil.parser
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test

#ex time:'2019-06-15 22:52:34.810649'

#def staff_required(login_url=None):
#    return user_passes_test(u.is_staff)

def staff_check(user):
    return user.is_staff

class tes:
	def __init__(self, b,st,x):
		self.b = b
		self.st = st
		self.x = x

def index(request):
	return render(request, 'base/index.html')

@login_required
def longGraphic(request):
	try:
		new_graph = longgraphic.objects.get(tipo=False)
		a = humidity.objects.all()
		b = [tes(float(a[i].media),float(a[i].sigma),a[i].date) for i in range(len(a))]
		b.sort(key=lambda nn: nn.x)
		st = [b[i].st for i in range(len(b))]
		x = [b[i].x for i in range(len(b))]
		b = [b[i].b for i in range(len(b))]
		g = graph.Graph(b,st,x,"humidity", float(globalvar.objects.get(name="LCh").value),float(globalvar.objects.get(name="LSCh").value),float(globalvar.objects.get(name="LICh").value),float(globalvar.objects.get(name="LSEh").value),float(globalvar.objects.get(name="LIEh").value),float(globalvar.objects.get(name="LCsh").value),float(globalvar.objects.get(name="LSCsh").value),float(globalvar.objects.get(name="LICsh").value))
		g.geraGrafico()
		new_graph.img='graphs/humidity.png'
		new_graph.cp = g.CP
		new_graph.cpk = g.CPK
		new_graph.dpm = g.DPM
		new_graph.LC = round(g.LC,4)
		new_graph.LSC = round(g.LSC,4)
		new_graph.LIC = round(g.LIC,4)
		new_graph.LCs = round(g.LCs,4)
		new_graph.LSCs = round(g.LSCs,4)
		new_graph.LICs = round(g.LICs,4)
		new_graph.LSE = round(g.LSE,4)
		new_graph.LIE = round(g.LIE,4)
		new_graph.rule1m = g.rule1HM
		new_graph.rule2m = g.rule2HM
		new_graph.rule3m = g.rule3HM
		new_graph.rule4m = g.rule4HM
		new_graph.rule1s = g.rule1HS
		new_graph.rule2s = g.rule1HS
		new_graph.rule3s = g.rule1HS
		new_graph.rule4s = g.rule1HS
		new_graph.save()
		
		
		new_graph = longgraphic.objects.get(tipo=True)
		a = temperature.objects.all()
		b = [tes(float(a[i].media),float(a[i].sigma),a[i].date) for i in range(len(a))]
		b.sort(key=lambda nn: nn.x)
		st = [b[i].st for i in range(len(b))]
		x = [b[i].x for i in range(len(b))]
		b = [b[i].b for i in range(len(b))]
		g = graph.Graph(b,st,x,"temperature", float(globalvar.objects.get(name="LCt").value),float(globalvar.objects.get(name="LSCt").value),float(globalvar.objects.get(name="LICt").value),float(globalvar.objects.get(name="LSEt").value),float(globalvar.objects.get(name="LIEt").value),float(globalvar.objects.get(name="LCst").value),float(globalvar.objects.get(name="LSCst").value),float(globalvar.objects.get(name="LICst").value))
		g.geraGrafico()
		new_graph.img='graphs/temperature.png'
		new_graph.cp = g.CP
		new_graph.cpk = g.CPK
		new_graph.dpm = g.DPM
		new_graph.LC = round(g.LC,4)
		new_graph.LSC = round(g.LSC,4)
		new_graph.LIC = round(g.LIC,4)
		new_graph.LCs = round(g.LCs,4)
		new_graph.LSCs = round(g.LSCs,4)
		new_graph.LICs = round(g.LICs,4)
		new_graph.LSE = round(g.LSE,4)
		new_graph.LIE = round(g.LIE,4)
		new_graph.rule1m = g.rule1HM
		new_graph.rule2m = g.rule2HM
		new_graph.rule3m = g.rule3HM
		new_graph.rule4m = g.rule4HM
		new_graph.rule1s = g.rule1HS
		new_graph.rule2s = g.rule1HS
		new_graph.rule3s = g.rule1HS
		new_graph.rule4s = g.rule1HS
		new_graph.save()
		
		
		longGraphics = longgraphic.objects.order_by('tipo')
		context = {'graphics':longGraphics}
	except:
		context = {}

	return render(request, 'base/long.html', context)

@user_passes_test(staff_check)
def recalculate(request):
	try:
		context = {	'LCt':globalvar.objects.get(name="LCt").value,
				'LSCt':globalvar.objects.get(name="LSCt").value,
				'LICt':globalvar.objects.get(name="LICt").value,
				'LCst':globalvar.objects.get(name="LCst").value,
				'LSCst':globalvar.objects.get(name="LSCst").value,
				'LICst':globalvar.objects.get(name="LICst").value,
				'LSEt':globalvar.objects.get(name="LSEt").value,
				'LIEt':globalvar.objects.get(name="LIEt").value,
				'LCh':globalvar.objects.get(name="LCh").value,
				'LSCh':globalvar.objects.get(name="LSCh").value,
				'LICh':globalvar.objects.get(name="LICh").value,
				'LCsh':globalvar.objects.get(name="LCsh").value,
				'LSCsh':globalvar.objects.get(name="LSCsh").value,
				'LICsh':globalvar.objects.get(name="LICsh").value,
				'LSEh':globalvar.objects.get(name="LSEh").value,
				'LIEh':globalvar.objects.get(name="LIEh").value
		}
	except:
		context = {}
	
	if(request.method == 'POST'):
		print(request.POST)
		date1 = str(dateutil.parser.parse(request.POST.__getitem__('date1')))+".000000"
		date2 = str(dateutil.parser.parse(request.POST.__getitem__('date2')))+".000000"
		if(request.POST.__getitem__('tipo')=='temperature'):
			a = temperature.objects.filter(date__range=[date1,date2])
		else:
			a = humidity.objects.filter(date__range=[date1,date2])
		if(len(a)==0):
			context['menssage'] = 'No samples found in between the specified dates'
			return render(request, 'base/recalculate.html', context)
		print(date1)
		print(date2)
		print(a)
		b = [tes(float(a[i].media),float(a[i].sigma),a[i].date) for i in range(len(a))]
		b.sort(key=lambda nn: nn.x)
		st = [b[i].st for i in range(len(b))]
		x = [b[i].x for i in range(len(b))]
		b = [b[i].b for i in range(len(b))]
		if(request.POST.__getitem__('tipo')=='temperature'):
			g = graph.Graph(b,st,x,"a", float(globalvar.objects.get(name="LCt").value),float(globalvar.objects.get(name="LSCt").value),float(globalvar.objects.get(name="LICt").value),float(globalvar.objects.get(name="LSEt").value),float(globalvar.objects.get(name="LIEt").value),float(globalvar.objects.get(name="LCst").value),float(globalvar.objects.get(name="LSCst").value),float(globalvar.objects.get(name="LICst").value))
		else:
			g = graph.Graph(b,st,x,"q", float(globalvar.objects.get(name="LCh").value),float(globalvar.objects.get(name="LSCh").value),float(globalvar.objects.get(name="LICh").value),float(globalvar.objects.get(name="LSEt").value),float(globalvar.objects.get(name="LIEt").value),float(globalvar.objects.get(name="LCsh").value),float(globalvar.objects.get(name="LSCsh").value),float(globalvar.objects.get(name="LICsh").value))
		g.recalculaLCs()
		if(request.POST.__getitem__('tipo')=='temperature'):
			LC = globalvar.objects.get(name="LCt")
			LC.value = round(g.LC,4)
			LC.save()
			LSC = globalvar.objects.get(name="LSCt")
			LSC.value = round(g.LSC,4)
			LSC.save()
			LIC = globalvar.objects.get(name="LICt")
			LIC.value = round(g.LIC,4)
			LIC.save()
			LCs = globalvar.objects.get(name="LCst")
			LCs.value = round(g.LCs,4)
			LCs.save()
			LSCs = globalvar.objects.get(name="LSCst")
			LSCs.value = round(g.LSCs,4)
			LSCs.save()
			LICs = globalvar.objects.get(name="LICst")
			LICs.value = round(g.LICs,4)
			LICs.save()
		else:
			LC = globalvar.objects.get(name="LCh")
			LC.value = round(g.LC,4)
			LC.save()
			LSC = globalvar.objects.get(name="LSCh")
			LSC.value = round(g.LSC,4)
			LSC.save()
			LIC = globalvar.objects.get(name="LICh")
			LIC.value = round(g.LIC,4)
			LIC.save()
			LCs = globalvar.objects.get(name="LCsh")
			LCs.value = round(g.LCs,4)
			LCs.save()
			LSCs = globalvar.objects.get(name="LSCsh")
			LSCs.value = round(g.LSCs,4)
			LSCs.save()
			LICs = globalvar.objects.get(name="LICsh")
			LICs.value = round(g.LICs,4)
			LICs.save()
		return render(request, 'base/recalculate.html', context)
	return render(request, 'base/recalculate.html', context)

@login_required
def new_graph(request):
	if(request.method == 'POST'):
		# ~ form = graphicForm(request.POST)
		# ~ if(form.is_valid()):
		print(request.POST)
		date1 = str(dateutil.parser.parse(request.POST.__getitem__('date1')))+".000000"
		date2 = str(dateutil.parser.parse(request.POST.__getitem__('date2')))+".000000"
		new_graph = graphic()
		# ~ new_graph = form.save(commit=False)
		# ~ date1 = new_graph.year+"-"+new_graph.month+"-"+new_graph.day+" "+new_graph.hour+":"+new_graph.minu+":00.000000"
		# ~ date2 = new_graph.year1+"-"+new_graph.month1+"-"+new_graph.day1+" "+new_graph.hour1+":"+new_graph.minu1+":00.000000"
		if(request.POST.__getitem__('tipo')=='temperature'):
			a = temperature.objects.filter(date__range=[date1,date2])
		else:
			a = humidity.objects.filter(date__range=[date1,date2])
		if(len(a)==0):
			context={'menssage':'No samples found in between the specified dates'}
			return render(request, 'base/new_graph.html', context)
		# ~ a = humidity.objects.filter(date__range=[str(dateutil.parser.parse(date1)),str(dateutil.parser.parse(date2))])
		print(date1)
		print(date2)
		print(a)
		b = [tes(float(a[i].media),float(a[i].sigma),a[i].date) for i in range(len(a))]
		b.sort(key=lambda nn: nn.x)
		st = [b[i].st for i in range(len(b))]
		x = [b[i].x for i in range(len(b))]
		b = [b[i].b for i in range(len(b))]
		new_graph.date1 = date1
		new_graph.date2 = date2
		new_graph.save()
		
		if(request.POST.__getitem__('tipo')=='temperature'):
			g = graph.Graph(b,st,x,new_graph.id, float(globalvar.objects.get(name="LCt").value),float(globalvar.objects.get(name="LSCt").value),float(globalvar.objects.get(name="LICt").value),float(globalvar.objects.get(name="LSEt").value),float(globalvar.objects.get(name="LIEt").value),float(globalvar.objects.get(name="LCst").value),float(globalvar.objects.get(name="LSCst").value),float(globalvar.objects.get(name="LICst").value))
		else:

django_app/base/templates/base/base.html
{% load static %}

<!doctype html>
<html lang='pt-BR'>
	<head>
		<meta charset="UTF-8">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="type="image/png""/>
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png"/>
		<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
		{% block head %}{% endblock head %}
		<link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
	</head>
	<body class = "body">
		<div class="page-header">
			<div class="logo">
				<a href="{% url 'base:index' %}">
				<img src="{% static 'img/logo.png' %}" alt="My image">
				</a>
			</div>
			<div class="left">
				<li><a href="{% url 'base:index' %}">Homepage</a></li>
				<li><a href="{% url 'base:new_graph' %}">New Graphic</a></li>
				<li><a href="{% url 'base:graphs' %}">Graphics</a></li>
				<li><a href="{% url 'base:recalculate' %}">Calibrate</a></li>
				<li><a href="{% url 'base:longGraphic' %}">Long Graphic</a></li>
			</div>
			<div class="right">
				{% if user.is_authenticated %}
					<div id=hello><li>Hello, {{ user.username }}!</li></div>
					<div id=logout><li><a href="{% url 'users:logout' %}">Logout</a></li></div>
				{% else %}
					<li><a href="{% url 'users:login' %}">Login</a></li>
					<li><a href="{% url 'users:register' %}">Register</a></li>
				{% endif %}
			</div>
		</div> <!-- end header -->
		<div class="content">
		{% block content %}{% endblock content %}
		</div> <!-- end content -->
	</body>
</html>

django_app/base/templates/base/index.html
{% extends "base/base.html" %}
{% load static %}
{% block head %}
 <title>CEP - Homepage</title>
<link rel="stylesheet" href="{% static 'css/graphs.css' %}"/>
{% endblock head %}

{% block content %}
<div class="graphic">
    {% if user.is_authenticated %}
		<p>Statistical process control of Temperature and humidity of a server room.</p>
	{% else %}
    	<p> Please proceed to login page if you want to see or make graphics </p>
		<p>Dev account:</p>
		<p>User: teste1</p>
		<p>Admin: Sulzbach</p>
		<p>Passwords(form both): justtest</p>
	{% endif %}
</div>
{% endblock content %}

django_app/base/templates/base/new_graph.html
{% extends "base/base.html" %}
{% load static %}
{% block head %}
<title>CEP - New Graphic</title>
<link rel="stylesheet" href="{% static 'css/graphs.css' %}"/>
{% endblock head %}

{% block content %}
<div class = graphic>
	<p>Add the name of the graphic and the period of the samples:</p>
	<form action="{% url 'base:new_graph' %}" method='post'>
		<input type="radio" name="tipo" value="humidity" checked> Humidity<br>
		<input type="radio" name="tipo" value="temperature"> Temperature<br><br>
		<p>Initial date:</p>
		<input type="datetime-local" id="date1"
	       name="date1" value = "2019-12-12T08:30">
		{% csrf_token %}
		<p>Final date:</p>
		<input type="datetime-local" id="date2"
	       name="date2" value = "2019-12-12T08:30"><br><br>
		<button name="submit">Generate</button>
	</form>
	<p>{{ menssage }}</p>
</div>
{% endblock content %}

django_app/base/templates/base/recalculate.html
{% extends "base/base.html" %}

{% load static %}

{% block head %}
 <title>CEP - Calibrate</title>
<link rel="stylesheet" href="{% static 'css/graphs.css' %}"/>
{% endblock head %}

{% block content %}
<div class = graphic>
	<div style="overflow-x:auto;">
		<table class="tables">
			<tr>
				<th colspan="3" id = "title">Control Limits for the temperature Graphic</th>
			</tr>
			<tr>
				<th id = "title"></th>
				<th id = "title">Mean</th>
				<th id = "title">Standard Deviation</th>
			</tr>
			<tr>
				<th>LC</th>
				<td>{{LCt}}</td>
				<td>{{LCst}}</td>
			</tr>
		  	<tr>
				<th>LSC</th>
				<td>{{LSCt}}</td>
				<td>{{LSCst}}</td>
		  	</tr>
		  	<tr>
				<th>LIC</th>
				<td>{{LICt}}</td>
				<td>{{LICst}}</td>
		  	</tr>
		  	<tr>
				<th>LSE</th>
				<td>{{LSEt}}</td>
				<td>-</td>
		  	</tr>
		  	<tr>
				<th>LIE</th>
				<td>{{LIEt}}</td>
				<td>-</td>
		  	</tr>
		</table>
		<br>
		<br>
		<table class="tables">
			<tr>
				<th colspan="3" id = "title">Control Limits for the humidity Graphic</th>
			</tr>
			<tr>
				<th id = "title"></th>
				<th id = "title">Mean</th>
				<th id = "title">Standard Deviation</th>
			</tr>
			<tr>
				<th>LC</th>
				<td>{{LCh}}</td>
				<td>{{LCsh}}</td>
			</tr>
		  	<tr>
				<th>LSC</th>
				<td>{{LSCh}}</td>
				<td>{{LSCsh}}</td>
		  	</tr>
		  	<tr>
				<th>LIC</th>
				<td>{{LICh}}</td>
				<td>{{LICsh}}</td>
		  	</tr>
		  	<tr>
				<th>LSE</th>
				<td>{{LSEh}}</td>
				<td>-</td>
		  	</tr>
		  	<tr>
				<th>LIE</th>
				<td>{{LIEh}}</td>
				<td>-</td>
		  	</tr>
		</table>
	</div>
	<br>
	<br>
	<p>Provide the information about the calibration that you want to do below.</p>
	<br>
	<form action="{% url 'base:recalculate' %}" method='post'>
		<p>Mark the type of graphic you want to calibrate:</p>
		<input type="radio" name="tipo" value="humidity" checked> Humidity<br>
		<input type="radio" name="tipo" value="temperature"> Temperature<br><br>
		<p>Initial date of data for calibration:</p>
		<input type="datetime-local" id="date1"
	       name="date1" value = "2019-12-10T08:30">
		{% csrf_token %}
		<p>Final date of data for calibration:</p>
		<input type="datetime-local" id="date2"
	       name="date2" value = "2019-12-10T08:30"><br><br>
		<button name="submit">Calibrate</button>
	</form>
	<p>{{ menssage }}</p>
</div>
{% endblock content %}